---
booktitle: Proceedings of the 2020 KDD Workshop on Causal Discovery
publisher: PMLR
series: Proceedings of Machine Learning Research
volume: 127
start: 2020-08-24
end: 2020-08-24
url: https://proceedings.mlr.press
published: 2020-08-19
layout: proceedings
issn: 2640-3498
id: CD2020
month: 0
cycles: false
bibtex_editor: Le, Thuc Duy and Liu, Lin and Zhang, Kun and K{\i}c{\i}man, Emre and
  Cui, Peng and Hyv\"{a}rinen, Aapo
editor:
- given: Thuc Duy
  family: Le
- given: Lin
  family: Liu
- given: Kun
  family: Zhang
- given: Emre
  family: Kıcıman
- given: Peng
  family: Cui
- given: Aapo
  family: Hyvärinen
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 2020 KDD Workshop on Causal Discovery
    Held in San Diego, CA, USA on 24 August 2020

  Published as Volume 127 by the Proceedings of Machine Learning Research on 19 August 2020.

  Volume Edited by:
    Thuc Duy Le
    Lin Liu
    Kun Zhang
    Emre Kıcıman
    Peng Cui
    Aapo Hyvärinen

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 24 Aug
author:
  name: PMLR
baseurl: "/v127"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v127
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Proceedings of the 2020 KDD Workshop on Causal Discovery
  url: 
  location: San Diego, CA, USA
  dates:
  - 2020-08-24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v127/bibliographyCD2020.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v127/bibliographyCD2020.bib
